import test from 'node:test';import assert from 'node:assert/strict';import{readFile}from'node:fs/promises';import uiHandler from'../api/dabbir-owner-decision-memory-ui.js';const read=p=>readFile(new URL('../'+p,import.meta.url),'utf8');
function render(){let body='',statusCode=200;const headers=new Map(),res={status(c){statusCode=c;return this},setHeader(k,v){headers.set(String(k).toLowerCase(),String(v));return this},end(v=''){body=String(v??'');return this}};uiHandler({method:'GET'},res);return{body,statusCode,headers}}
test('memory is owner-confirmed low-risk and versioned',async()=>{const s=await read('db/dabbir_owner_decision_memory_v1.sql');assert.match(s,/explicit_confirmation boolean not null default false/i);assert.match(s,/risk_class text not null check\(risk_class='LOW'\)/i);assert.match(s,/m\.role='owner'/i);assert.match(s,/having count\(\*\)>=3/i);assert.match(s,/unique\(business_id,action_key,version\)/i);assert.match(s,/force row level security/i)});
test('observations never grant write access to clients',async()=>{const s=await read('db/dabbir_owner_decision_memory_v1.sql');assert.match(s,/revoke all on public\.dabbir_owner_decision_observations,public\.dabbir_owner_policy_versions,public\.dabbir_owner_policy_audit from public,anon,authenticated/i);assert.match(s,/grant select on public\.dabbir_owner_decision_observations,public\.dabbir_owner_policy_versions,public\.dabbir_owner_policy_audit to authenticated/i)});
test('money legal KYC and higher risk cannot become learned authority',async()=>{const s=await read('db/dabbir_owner_decision_memory_v1.sql');assert.match(s,/v_risk<>'LOW'.*POLICY_MEMORY_LOW_RISK_ONLY/is);for(const w of['payment','refund','payout','withdraw','transfer','billing','legal','kyc','identity','bank','discount','price'])assert.ok(s.includes(w));assert.match(s,/SENSITIVE_ACTION_NOT_LEARNABLE/)});
test('candidate requires exact action decision value and JSON bounds',async()=>{const s=await read('db/dabbir_owner_decision_memory_v1.sql');assert.match(s,/group by o\.action_key,o\.decision_key,o\.decision_value,o\.match_bounds/i);assert.match(s,/o\.match_bounds=coalesce\(p_match_bounds,'\{\}'::jsonb\)/i);assert.match(s,/v_count<3 then raise exception 'INSUFFICIENT_MATCHING_OBSERVATIONS'/i)});
test('runtime only suppresses exact low-priority OWNER_DECISION handoff',async()=>{const s=await read('db/dabbir_owner_decision_memory_runtime_v1.sql');assert.match(s,/upper\(coalesce\(p_route_class,''\)\)<>'OWNER_DECISION'/i);assert.match(s,/coalesce\(p_priority,100\)>40/i);assert.match(s,/jsonb_build_object\('route_class','OWNER_DECISION','reason',v_reason,'max_priority',40\)/i);assert.match(s,/v_match\.decision_value<>'continue_with_ai'/i);assert.match(s,/external_side_effects',false/i);assert.match(s,/handoff_created',false/i)});
test('runtime false-match guard blocks sensitive reasons',async()=>{const s=await read('db/dabbir_owner_decision_memory_runtime_v1.sql');for(const w of['payment','refund','payout','withdraw','transfer','billing','invoice','legal','kyc','identity','bank','discount','price','money','cash','tax','vat'])assert.ok(s.includes(w))});
test('owner observation requires no human intervention from any human',async()=>{const s=await read('db/dabbir_owner_decision_memory_runtime_v1.sql');assert.match(s,/v_role='owner'/i);assert.match(s,/v_handoff\.route_class='OWNER_DECISION'/i);assert.match(s,/coalesce\(v_handoff\.priority,100\)<=40/i);assert.match(s,/msg\.sender_type='human'/i);assert.doesNotMatch(s,/msg\.sender_user_id=auth\.uid\(\)/i);assert.match(s,/if not v_human_reply_exists/i)});
test('pause revoke and competing active policy fail closed',async()=>{const s=await read('db/dabbir_owner_decision_memory_v1.sql');assert.match(s,/REVOKED_POLICY_IMMUTABLE/);assert.match(s,/ANOTHER_ACTIVE_POLICY_EXISTS/);assert.match(s,/p\.state='ACTIVE'/i)});
test('API requires owner and same-origin explicit activation',async()=>{const s=await read('api/owner-decision-memory.js');assert.match(s,/membership\.role!=='owner'/);assert.match(s,/requireSameOrigin\(req\)/);assert.match(s,/SENSITIVE_ACTION_NOT_LEARNABLE/);assert.match(s,/explicit_owner_confirmation:true/)});
test('UI explains explicit approval and generated client parses',()=>{const r=render();assert.equal(r.statusCode,200);assert.equal(r.headers.get('x-dabbir-owner-decision-memory-ui'),'v1');assert.match(r.body,/لا تُفعّل أي سياسة إلا بموافقتك الصريحة/);assert.match(r.body,/Nothing activates without your explicit approval/);assert.doesNotThrow(()=>new Function(r.body))});
test('app recovery loads policy UI after owner action center',async()=>{const s=await read('api/app-recovery.js');assert.match(s,/\/api\/dabbir-owner-decision-memory-ui/);assert.ok(s.indexOf('/api/dabbir-owner-decision-memory-ui')>s.indexOf('/api/owner-action-center-ui'))});
