import test from 'node:test';import assert from 'node:assert/strict';
import {understandConversation as understand,resolveOrdinal,semanticPlannerContext} from '../api/_dabbir-semantic-engine.js';
import {evaluationCases,context,now,ids,offered,appointments} from './fixtures/understanding/cases.mjs';
export function runCase(c){let previous,result;for(const body of c.turns){result=understand({context:context({...c.extra,batch_messages:[{body}]}),previous,now});previous=result.state;}return result;}
for(const c of evaluationCases)test('understanding v2: '+c.id,()=>{const r=runCase(c);for(const [k,v] of Object.entries(c.expected)){const actual=k==='action'?r.decision.action:k==='intent'?r.state.intent:k==='missing'?r.state.missing_fields:k==='source'?r.state.entities.time?.source:r.state.entities[k]?.value??null;assert.deepEqual(actual,v,`${k}: ${c.turns.join(' -> ')}`);}});
test('model inference alone never authorizes a mutation',()=>{const r=understand({context:context({batch_messages:[{body:'hello'}],pending_state:offered}),now,proposal:{action:'CREATE_BOOKING',confidence:1,intent:'BOOKING'}});assert.notEqual(r.decision.action,'CREATE_BOOKING');});
test('provider context contains no customer/business/conversation ids',()=>{const r=understand({context:context({batch_messages:[{body:'ابا غسيل باجر'}]}),now});const raw=JSON.stringify(semanticPlannerContext(context(),r.state));for(const id of Object.values(ids))assert.ok(!raw.includes(id));});
test('state from another tenant or customer is never carried forward',()=>{const r=runCase({turns:['ابا غسيل باجر']});r.state.scope.customer_id='alien';const next=understand({context:context({batch_messages:[{body:'الساعة 18:00'}]}),previous:r.state,now});assert.equal(next.state.entities.service,undefined);});
test('affirmative ordinal resolution rejects multiple references',()=>{assert.deepEqual(resolveOrdinal('الأول أو الثاني'),{index:null,ambiguous:true,mentioned:true});assert.equal(resolveOrdinal('الغ الثاني مب الأول').index,1);});
test('selection from an unpresented list cannot mutate',()=>{const r=understand({context:context({batch_messages:[{body:'الثاني'}],pending_state:{...offered,payload:{...offered.payload,presented:false}}}),now});assert.notEqual(r.decision.action,'CREATE_BOOKING');});
test('an explicit other branch never falls back to this conversation branch',()=>{const r=understand({context:context({branches:[{id:'other-branch',name:'دبي'}],batch_messages:[{body:'ابا غسيل باجر الساعة 18:00 فرع دبي'}]}),now});assert.equal(r.decision.action,'CLARIFY');assert.ok(r.state.unresolved_references.includes('branch'));});
test('vehicle memory accepts only a verified scoped source',()=>{const r=understand({context:context({verified_memory:[{business_id:ids.business,customer_id:ids.customer,memory_key:'known_vehicle',value:{id:'v'},status:'verified',source:'AI_INFERENCE',confidence:1,last_confirmed_at:now.toISOString()}],batch_messages:[{body:'خذ نفس السيارة'}]}),now});assert.equal(r.state.entities.vehicle,undefined);});
test('a previous completed booking is not repeated by a thank-you message',()=>{const r=understand({context:context({pending_state:offered,batch_messages:[{body:'الثاني'}]}),now});r.state.last_verified_action={action:'CREATE_BOOKING',at:now.toISOString()};const next=understand({context:context({batch_messages:[{body:'شكرا'}]}),previous:r.state,now:new Date(now.getTime()+1000)});assert.equal(next.decision.action,'REPLY');assert.equal(next.state.entities.slot,undefined);});
test('reschedule retains the appointment while the next ordinal selects its offered slot',()=>{const first=understand({context:context({upcoming_appointments:[appointments[0]],batch_messages:[{body:'غير الموعد باجر الساعة 18:00'}]}),now});assert.equal(first.decision.action,'CHECK_AVAILABILITY');const next=understand({context:context({upcoming_appointments:[appointments[0]],pending_state:{...offered,payload:{...offered.payload,mode:'reschedule',appointment_id:appointments[0].id}},batch_messages:[{body:'الثاني'}]}),previous:first.state,now});assert.equal(next.decision.action,'RESCHEDULE_BOOKING');assert.equal(next.state.entities.appointment.value,appointments[0].id);assert.equal(next.state.entities.slot.value,1);});
for(const body of ['لا تحجز الثاني','do not book the second one','كم سعر الثاني','الثاني؟','when is the second one'])test('question or negation cannot confirm a slot: '+body,()=>{const r=understand({context:context({pending_state:offered,batch_messages:[{body}]}),now});assert.notEqual(r.decision.action,'CREATE_BOOKING');assert.notEqual(r.decision.action,'RESCHEDULE_BOOKING');});
