import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {capabilityShadowVerdict} from '../api/_dabbir-capability-registry.js';
import {safeKnowledgeContext,mineProductionFailures} from '../api/_dabbir-intelligence-flywheel.js';
const migration=fs.readFileSync(new URL('../supabase/migrations/20260909030000_dabbir_intelligence_flywheel_v1.sql',import.meta.url),'utf8');
const leastPrivilege=fs.readFileSync(new URL('../supabase/migrations/20260909035500_dabbir_intelligence_flywheel_least_privilege_v1.sql',import.meta.url),'utf8');
const clarificationTruth=fs.readFileSync(new URL('../supabase/migrations/20260909040500_dabbir_intelligence_flywheel_clarification_truth_v1.sql',import.meta.url),'utf8');

test('migration is additive, tenant private and eval cases contain no raw message body',()=>{assert.match(migration,/create extension if not exists vector with schema extensions/i);assert.match(migration,/embedding extensions\.vector\(768\)/i);assert.match(migration,/using hnsw/i);assert.match(migration,/using gin/i);assert.match(migration,/force row level security/ig);assert.match(migration,/revoke all on table public\.dabbir_ai_eval_cases from public, anon, authenticated/i);const block=migration.match(/create table if not exists public\.dabbir_ai_eval_cases \([\s\S]*?\n\);/i)?.[0]||'';assert.doesNotMatch(block,/\b(body|message_text|prompt|transcript)\b/i)});
test('least-privilege follow-up removes Supabase default service grants before exact runtime grants',()=>{for(const table of ['dabbir_business_knowledge_embeddings','dabbir_ai_eval_cases','dabbir_capability_registry','dabbir_ai_failure_clusters','dabbir_ai_improvement_proposals'])assert.match(leastPrivilege,new RegExp(`revoke all on table public\\.${table} from service_role`,'i'));assert.match(leastPrivilege,/grant select, insert, update, delete on table public\.dabbir_business_knowledge_embeddings to service_role/i);assert.match(leastPrivilege,/grant select, insert, update on table public\.dabbir_ai_eval_cases to service_role/i);assert.match(leastPrivilege,/grant select on table public\.dabbir_capability_registry to service_role/i);assert.match(leastPrivilege,/grant select, insert, update on table public\.dabbir_ai_failure_clusters to service_role/i);assert.match(leastPrivilege,/grant select, insert, update on table public\.dabbir_ai_improvement_proposals to service_role/i);assert.doesNotMatch(leastPrivilege,/grant[^;]*(truncate|trigger|references)[^;]*to service_role/i)});
test('clarification mining preserves necessary questions and only mines repeated or unresolved friction',()=>{assert.match(clarificationTruth,/clarification_count_value>=2 or p\.unresolved_count_value>0/i);assert.match(clarificationTruth,/then 'CLARIFICATION_FRICTION'/i);assert.match(clarificationTruth,/when upper\(coalesce\(p\.metrics->>'action',''\)\)='CLARIFY' then null/i);const safeClarify=clarificationTruth.indexOf("when upper(coalesce(p.metrics->>'action',''))='CLARIFY' then null");const lowConfidence=clarificationTruth.indexOf("when p.operational_confidence_value<0.65 then 'LOW_OPERATIONAL_CONFIDENCE'");assert.ok(safeClarify>=0&&lowConfidence>safeClarify);assert.match(clarificationTruth,/set status='dismissed'/i);assert.match(clarificationTruth,/set status='superseded'/i);assert.match(clarificationTruth,/where status='open'/i);assert.doesNotMatch(clarificationTruth,/upper\(coalesce\(p\.metrics->>'action',''\)\)='CLARIFY'\s+then 'CLARIFICATION'/i)});
test('clarification definer functions remain service-role only',()=>{for(const signature of ['public\\.dabbir_ai_eval_ingest_recent_v1\\(interval,integer\\)','public\\.dabbir_ai_failure_mine_v1\\(interval\\)']){assert.match(clarificationTruth,new RegExp(`revoke all on function ${signature} from public, anon, authenticated`,'i'));assert.match(clarificationTruth,new RegExp(`grant execute on function ${signature} to service_role`,'i'))}});
test('failure miner is proposal-only and cannot auto-apply',()=>{assert.match(migration,/auto_apply',false/i);assert.match(migration,/status text not null default 'proposed'/i);assert.match(clarificationTruth,/auto_apply',false/i);assert.doesNotMatch(migration,/update\s+public\.dabbir_business_knowledge\s+set/i);assert.doesNotMatch(clarificationTruth,/update\s+public\.dabbir_business_knowledge\s+set/i)});
test('failure miner safely parses historical metric drift instead of crashing on malformed JSON scalars',()=>{assert.match(migration,/char_length\(coalesce\(e\.metrics->>'operational_confidence',''\)\)<=32/i);assert.match(migration,/char_length\(coalesce\(metrics->>'semantic_confidence',''\)\)<=32/i);assert.match(migration,/lower\(coalesce\(metrics->>'voice',''\)\)='true'/i);assert.match(clarificationTruth,/char_length\(coalesce\(e\.metrics->>'clarification_count',''\)\)<=12/i);assert.match(clarificationTruth,/char_length\(coalesce\(e\.metrics->>'unresolved_count',''\)\)<=12/i);assert.doesNotMatch(migration,/coalesce\(\(e\.metrics->>'operational_confidence'\)::numeric/i);assert.doesNotMatch(migration,/coalesce\(\(metrics->>'(?:semantic_confidence|operational_confidence)'\)::numeric/i);assert.doesNotMatch(migration,/\(metrics->>'voice'\)::boolean/i)});
test('capability registry starts shadow-only and cannot become execution authority from JS',()=>{const verdict=capabilityShadowVerdict({decision:{action:'CREATE_BOOKING'},capabilities:[{tool_name:'CREATE_BOOKING',enabled:true,risk_level:'MEDIUM',verification_mode:'DATABASE_READBACK'}]});assert.equal(verdict.mode,'SHADOW');assert.equal(verdict.would_block,false);const absent=capabilityShadowVerdict({decision:{action:'CANCEL_BOOKING'},capabilities:[]});assert.equal(absent.would_block,true)});
test('planner context truncates retrieved knowledge',()=>{const rows=safeKnowledgeContext([{knowledge_key:'x'.repeat(300),knowledge_type:'policy',content:'a'.repeat(3000),score:.9}]);assert.equal(rows[0].knowledge_key.length,180);assert.equal(rows[0].content.length,1200)});
test('production failure mining delegates to database without applying changes',async()=>{let args;const result=await mineProductionFailures({rpc:async(name,p)=>{args=[name,p];return {ok:true,auto_apply:false}},since:'48 hours'});assert.equal(args[0],'dabbir_ai_failure_mine_v1');assert.equal(result.auto_apply,false)});

test('legacy semantic planner consumes only guarded business-scoped RAG behind the canonical conversation boundary',()=>{
  const core=fs.readFileSync(new URL('../api/_dabbir-whatsapp-ai-core.js',import.meta.url),'utf8');
  const source=fs.readFileSync(new URL('../api/_dabbir-conversation-runtime.js',import.meta.url),'utf8');
  assert.match(core,/\.\/_dabbir-conversation-runtime\.js/);
  assert.doesNotMatch(core,/retrieveDabbirKnowledge/);
  assert.match(source,/import \{retrieveDabbirKnowledge\} from '\.\/_dabbir-knowledge-rag\.js'/);
  assert.match(source,/retrieveDabbirKnowledge\(\{businessId:c\.business\.id,query:message,rpc,env:process\.env,fetchImpl:fetch,limit:5\}\)/);
  assert.match(source,/context:\{\.\.\.safeContext,retrieved_business_knowledge:retrieved\}/);
  assert.doesNotMatch(source,/retrieved_business_knowledge[^\n]{0,200}(?:CREATE_BOOKING|CANCEL_BOOKING|RESCHEDULE_BOOKING)\s*\(/);
});
