import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const read=path=>readFile(new URL('../'+path,import.meta.url),'utf8');
const [bridge,actionBridge,supportBridge,teamBridge,copilot,logout,ui14,gateway,migration,searchMigration,supportMigration]=await Promise.all([
  read('api/owner-platform-bridge.js'),read('api/owner-action-bridge.js'),read('api/owner-support-bridge.js'),read('api/owner-team-bridge.js'),read('api/owner-platform-copilot.js'),read('api/auth/owner-logout.js'),read('api/owner-command-center-v14.js'),read('api/owner-dashboard-gateway.js'),read('supabase/migrations/20260830102000_dabbir_platform_owner_action_bridge_v2.sql'),read('supabase/migrations/20260827155045_dabbir_platform_customer_search_escape_fix_v3.sql'),read('supabase/migrations/20260830112000_dabbir_platform_owner_support_summary_v1.sql'),
]);

test('owner platform read bridge stays owner-session gated and read only',()=>{assert.match(bridge,/__Host-dabbir_owner_session/);assert.match(bridge,/owner_session_verify/);assert.match(bridge,/role==='platform_owner'/);assert.match(bridge,/req\.method!=='GET'/);assert.doesNotMatch(ui14,/SUPABASE_SERVICE_ROLE_KEY/);assert.match(bridge,/operations:operations\(products,inventory,orders\)/);assert.match(bridge,/recognized_sales_aed/)});
test('owner action bridge is explicitly allowlisted and confirmed',()=>{assert.match(actionBridge,/requireSameOrigin/);assert.match(actionBridge,/confirmation!=='EXECUTE'/);for(const action of ['set_inventory','set_product_active','cancel_pending_order','set_service_active','support_create_case','support_add_note','support_set_status'])assert.match(actionBridge,new RegExp(action));assert.doesNotMatch(actionBridge,/create_expense|refund|checkout|disconnect|set_member_role|access_token_ciphertext/)});
test('database action function is service-role only and audited atomically',()=>{assert.match(migration,/security definer/);assert.match(migration,/grant execute[\s\S]*service_role/);assert.match(migration,/dabbir_platform_owner_audit/);assert.doesNotMatch(migration,/stripe|refund|create_expense|set_member_role/)});
test('customer search contract remains accounts plus businesses',()=>{assert.match(searchMigration,/jsonb_build_object\('accounts',v_result,'count',v_count\)/);assert.match(ui14,/Array\.isArray\(j\.accounts\)/);assert.match(ui14,/Array\.isArray\(x\.businesses\)/)});
test('unified v14 has no legacy iframe or owner-business auth dependency',()=>{assert.match(ui14,/v14-unified/);for(const hash of ['home','customers','operations','ai','governance','system'])assert.match(ui14,new RegExp(`id=\\"${hash}\\"`));assert.match(ui14,/owner-platform-bridge\?business_id/);assert.match(ui14,/owner-support-bridge\?customer_no/);assert.match(ui14,/owner-team-bridge\?business_id/);assert.match(ui14,/owner-platform-copilot/);assert.match(ui14,/owner-action-bridge/);assert.doesNotMatch(ui14,/<iframe/);assert.doesNotMatch(ui14,/\/api\/owner-operations\?business_id/);assert.match(gateway,/owner-command-center-v14\.js/)});
test('owner support read bridge is OTP owner-session gated and service-role RPC only',()=>{assert.match(supportBridge,/owner_session_verify/);assert.match(supportBridge,/dabbir_platform_owner_support_summary_v1/);assert.match(supportMigration,/security definer/);assert.match(supportMigration,/grant execute[\s\S]*service_role/)});
test('owner team bridge is handler-read-only and never mutates team records',()=>{assert.match(teamBridge,/req\.method!=='GET'/);assert.match(teamBridge,/owner_session_verify/);assert.match(teamBridge,/dabbir_memberships\?select=/);assert.match(teamBridge,/dabbir_employee_invitations\?select=/);assert.doesNotMatch(teamBridge,/PATCH|set_member_role|role_changed|employee_removed|employee_suspended|employee_reactivated/)});
test('owner copilot is same-origin owner-session gated and grounded',()=>{assert.match(copilot,/requireSameOrigin/);assert.match(copilot,/owner_session_verify/);assert.match(copilot,/generateDABBIRAiReply/);assert.match(copilot,/DETERMINISTIC_VERIFIED_FALLBACK/);assert.match(copilot,/FREE_TIER_ONLY/)});
test('owner logout clears owner cookie through same-origin POST',()=>{assert.match(logout,/requireSameOrigin/);assert.match(logout,/req\.method!=='POST'/);assert.match(logout,/Max-Age=0/)});
