import test from 'node:test';
import assert from 'node:assert/strict';
import { evaluateReadiness } from '../scripts/dabbir-readiness-gate.mjs';

const publicContract={deployment:{public_launch_domain:'dabbir.example',domain_access:'PUBLIC',production_runtime_policy:'PUBLIC_PRODUCTION',project_live:true}};
const protectedContract={deployment:{public_launch_domain:null,domain_access:'VERCEL_AUTH_PROTECTED',production_runtime_policy:'FAIL_CLOSED_PREVIEW_ONLY',project_live:false}};
const complete={expected_main_sha:'abc123',production_deployment:{id:'dpl_ok',state:'READY',source_commit:'abc123'},end_to_end_journey:{verdict:'PASS',real_external_connection:true,real_inbound_message:true,approved_reply_verified:true},iphone_safari_ar:{verdict:'PASS'},iphone_safari_en:{verdict:'PASS'},monitoring:{runtime_errors_checked:true,alert_delivery_verified:true},critical_gates:{security:'PASS',financial:'PASS',legal:'PASS'},live_evidence:{evidence:{whatsapp:{operational_connections:1,verified_connections:1,inbound_conversations:4,inbound_messages:8,verified_replies:3,connection_success_rate:.8,setup_time_seconds:150},handoffs:{rate:.25,routed_to_human:1},satisfaction:{samples:4,score:4.5}}}};

test('protected prelaunch is blocked without pretending production passed',()=>{const report=evaluateReadiness({contract:protectedContract,evidence:{},productionOrigin:''});assert.equal(report.verdict,'BLOCKED');assert.equal(report.gates.find(x=>x.key==='public_launch_contract')?.state,'BLOCKED')});
test('complete external evidence can reach READY',()=>{const report=evaluateReadiness({contract:publicContract,evidence:complete,productionOrigin:'https://dabbir.example'});assert.equal(report.verdict,'READY');assert.equal(report.blocker_count,0)});
test('web-only journey can never satisfy the external BAR-12 journey',()=>{const evidence=structuredClone(complete);evidence.end_to_end_journey={verdict:'PASS',real_external_connection:false,real_inbound_message:false,approved_reply_verified:false};const report=evaluateReadiness({contract:publicContract,evidence,productionOrigin:'https://dabbir.example'});assert.equal(report.verdict,'BLOCKED');assert.equal(report.gates.find(x=>x.key==='end_to_end_journey')?.state,'BLOCKED')});
test('null and empty KPI evidence stay insufficient instead of becoming numeric zero',()=>{for(const missing of [null,undefined,'']){const evidence=structuredClone(complete);evidence.live_evidence.evidence.whatsapp.connection_success_rate=missing;evidence.live_evidence.evidence.whatsapp.setup_time_seconds=missing;evidence.live_evidence.evidence.handoffs.rate=missing;evidence.live_evidence.evidence.satisfaction={samples:0,score:missing};evidence.monitoring.alert_delivery_verified=false;const report=evaluateReadiness({contract:publicContract,evidence,productionOrigin:'https://dabbir.example'});assert.equal(report.gates.find(x=>x.key==='connection_success_metric')?.state,'INSUFFICIENT_EVIDENCE');assert.equal(report.gates.find(x=>x.key==='setup_time_metric')?.state,'INSUFFICIENT_EVIDENCE');assert.equal(report.gates.find(x=>x.key==='human_handoff_metric')?.state,'INSUFFICIENT_EVIDENCE');assert.equal(report.gates.find(x=>x.key==='satisfaction_metric')?.state,'INSUFFICIENT_EVIDENCE');assert.equal(report.gates.find(x=>x.key==='alerting')?.state,'INSUFFICIENT_EVIDENCE')}});
test('production commit mismatch is a hard blocker',()=>{const evidence=structuredClone(complete);evidence.production_deployment.source_commit='wrong';const report=evaluateReadiness({contract:publicContract,evidence,productionOrigin:'https://dabbir.example'});assert.equal(report.gates.find(x=>x.key==='production_deployment')?.state,'BLOCKED')});
