import test,{before,after} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {PGlite} from '@electric-sql/pglite';
import {understandConversation} from '../api/_dabbir-semantic-engine.js';import {context,ids,offered,now as evalNow} from './fixtures/understanding/cases.mjs';
const db=new PGlite();const batch='90000000-0000-4000-8000-000000000001',lock='90000000-0000-4000-8000-000000000002',message='90000000-0000-4000-8000-000000000003',owner='10000000-0000-4000-8000-000000000001',otherOwner='10000000-0000-4000-8000-000000000002';
const rpc=async(name,args)=>{const r=await db.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args);return r.rows[0].result;};
const load=()=>rpc('dabbir_semantic_load_v2',[batch,lock]);
async function reset(){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.role','service_role',false)");await db.exec('delete from dabbir_whatsapp_outbound_reservations;delete from dabbir_ai_understanding_events;delete from dabbir_customer_memory;delete from dabbir_ai_action_ledger;delete from dabbir_appointments;delete from dabbir_ai_conversation_state;delete from dabbir_message_batch_items;delete from dabbir_messages;delete from dabbir_message_batches;delete from dabbir_handoffs;');
 await db.query("update dabbir_conversations set state='ai_active',understanding_revision=0 where id=$1",[ids.conversation]);
 await db.query('insert into dabbir_messages(id,business_id,conversation_id) values($1,$2,$3)',[message,ids.business,ids.conversation]);
 await db.query('insert into dabbir_message_batches(id,business_id,conversation_id,customer_id,lock_token) values($1,$2,$3,$4,$5)',[batch,ids.business,ids.conversation,ids.customer,lock]);
 await db.query('insert into dabbir_message_batch_items(batch_id,business_id,message_id,ordinal) values($1,$2,$3,1)',[batch,ids.business,message]);
 await db.query("insert into dabbir_whatsapp_outbound_reservations(business_id,conversation_id,provider_message_id,state) values($1,$2,'verified-offer','SENT')",[ids.business,ids.conversation]);
}
function bookingState(){return understandConversation({context:context({batch_messages:[{body:'الثاني'}],pending_state:offered}),now:evalNow}).state;}
async function commit(state=bookingState(),expected=0){const l=await load();return rpc('dabbir_semantic_commit_v2',[batch,lock,expected,l.message_revision,state,{action:'CREATE_BOOKING'}]);}
before(async()=>{await db.exec(fs.readFileSync(new URL('./fixtures/understanding/database.sql',import.meta.url),'utf8'));await db.exec(fs.readFileSync(new URL('../supabase/migrations/20260908025920_dabbir_understanding_engine_v2.sql',import.meta.url),'utf8'));
 await db.query('insert into auth.users(id) values($1),($2)',[owner,otherOwner]);
 await db.query('insert into dabbir_businesses(id) values($1),($2)',[ids.business,ids.other]);
 await db.query("insert into dabbir_memberships values($1,$2,'owner','active'),($3,$4,'owner','active')",[ids.business,owner,ids.other,otherOwner]);
 await db.query('insert into dabbir_customers(id,business_id) values($1,$2)',[ids.customer,ids.business]);
 await db.query('insert into dabbir_business_branches(id,business_id) values($1,$2)',[ids.branch,ids.business]);
 await db.query('insert into dabbir_conversations(id,business_id,customer_id,branch_id) values($1,$2,$3,$4)',[ids.conversation,ids.business,ids.customer,ids.branch]);
 await db.query('insert into dabbir_services(id,business_id) values($1,$2)',[ids.service,ids.business]);
 await db.query('insert into dabbir_workers(id,business_id) values($1,$2)',[ids.worker,ids.business]);
});after(()=>db.close());
test('database: semantic state persists once per batch with audited provenance',async()=>{await reset();const s=bookingState();const c=await commit(s);assert.equal(c.version,1);const again=await commit(s);assert.equal(again.replay,true);assert.equal((await load()).version,1);assert.equal((await db.query('select count(*) n from dabbir_ai_understanding_events')).rows[0].n,1);});
test('database: cross-tenant state and mismatched customer are rejected',async()=>{await reset();const s=bookingState();s.scope.business_id=ids.other;await assert.rejects(commit(s),/SEMANTIC_STATE_SCOPE_INVALID/);s.scope.business_id=ids.business;s.scope.customer_id=owner;await assert.rejects(commit(s),/SEMANTIC_STATE_SCOPE_INVALID/);});
test('database: compound conversation foreign key rejects cross-business insert',async()=>{await reset();await assert.rejects(db.query('insert into dabbir_ai_conversation_state(business_id,conversation_id) values($1,$2)',[ids.other,ids.conversation]),/foreign key/);});
test('database: stale worker cannot commit after a new inbound at equal timestamp',async()=>{await reset();const l=await load();await db.query('insert into dabbir_messages(business_id,conversation_id,created_at) select business_id,conversation_id,created_at from dabbir_messages where id=$1',[message]);await assert.rejects(rpc('dabbir_semantic_commit_v2',[batch,lock,0,l.message_revision,bookingState(),{}]),/SEMANTIC_SUPERSEDED/);});
test('database: new message between commit and mutation blocks the old intent',async()=>{await reset();await commit();await db.query('insert into dabbir_messages(business_id,conversation_id)values($1,$2)',[ids.business,ids.conversation]);await assert.rejects(rpc('dabbir_semantic_execute_v2',[batch,lock,1,'CREATE_BOOKING']),/SEMANTIC_SUPERSEDED/);assert.equal((await db.query('select count(*) n from dabbir_appointments')).rows[0].n,0);});
test('database: expired lock and wrong lock token fail closed',async()=>{await reset();await assert.rejects(rpc('dabbir_semantic_load_v2',[batch,message]),/SEMANTIC_BATCH_LOCK_INVALID/);await db.query("update dabbir_message_batches set locked_until=now()-interval '1 minute'");await assert.rejects(load(),/SEMANTIC_BATCH_LOCK_INVALID/);});
test('database: human takeover blocks state and mutations',async()=>{await reset();await commit();await db.query("update dabbir_conversations set state='human_active'");await assert.rejects(rpc('dabbir_semantic_execute_v2',[batch,lock,1,'CREATE_BOOKING']),/AI_BLOCKED_BY_HUMAN_TAKEOVER/);});
test('database: incomplete or low confidence state cannot mutate',async()=>{await reset();let s=bookingState();s.missing_fields=['location'];await commit(s);await assert.rejects(rpc('dabbir_semantic_execute_v2',[batch,lock,1,'CREATE_BOOKING']),/SEMANTIC_MUTATION_BLOCKED/);await reset();s=bookingState();s.operational_confidence=.5;await commit(s);await assert.rejects(rpc('dabbir_semantic_execute_v2',[batch,lock,1,'CREATE_BOOKING']),/SEMANTIC_MUTATION_BLOCKED/);});
test('database: inferred or fabricated slot cannot create an appointment',async()=>{await reset();const s=bookingState();s.entities.slot.source='AI_INFERENCE';await commit(s);await rpc('dabbir_semantic_set_pending_v2',[batch,lock,1,'choose_slot',offered.payload]);await assert.rejects(rpc('dabbir_semantic_execute_v2',[batch,lock,1,'CREATE_BOOKING']),/SEMANTIC_SLOT_UNCONFIRMED/);});
test('database: guarded booking readback, safe memory and idempotent retry',async()=>{await reset();await commit();await rpc('dabbir_semantic_set_pending_v2',[batch,lock,1,'choose_slot',offered.payload]);const r=await rpc('dabbir_semantic_execute_v2',[batch,lock,1,'CREATE_BOOKING']);assert.equal(r.verified,true);const repeated=await rpc('dabbir_semantic_execute_v2',[batch,lock,1,'CREATE_BOOKING']);assert.equal(repeated.idempotent_replay,true);assert.equal(repeated.appointment_id,r.appointment_id);assert.equal((await db.query('select count(*) n from dabbir_appointments')).rows[0].n,1);const m=(await load()).verified_memory;assert.equal(m.length,1);assert.equal(m[0].status,'verified');assert.equal(m[0].value.id,ids.service);});
test('database: PUBLIC and anonymous roles cannot execute V2 operational RPCs',async()=>{await reset();const rows=(await db.query("select proname,has_function_privilege('anon',p.oid,'EXECUTE') a,has_function_privilege('authenticated',p.oid,'EXECUTE') u from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and proname like 'dabbir_semantic_%'")).rows;assert.ok(rows.length>=5);for(const r of rows){assert.equal(r.a,false,r.proname);assert.equal(r.u,false,r.proname);}await db.exec('set role anon');await assert.rejects(load(),/permission denied/);await db.exec('reset role');});
test('database: owner proposal is inactive until explicit approval, then revoke and rollback are audited',async()=>{await reset();await db.query("select set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claim.role','authenticated',false)",[owner]);await db.exec('set role authenticated');const p=await rpc('dabbir_knowledge_propose_v2',[ids.business,ids.conversation,null,'service','VIP',ids.service]);assert.equal(p.active,false);const approved=await rpc('dabbir_knowledge_review_v2',[ids.business,p.id,'approve']);assert.equal(approved.active,true);await rpc('dabbir_knowledge_review_v2',[ids.business,p.id,'revoke']);const rolled=await rpc('dabbir_knowledge_review_v2',[ids.business,p.id,'rollback']);assert.equal(rolled.active,true);assert.ok(rolled.version>approved.version);const audit=await db.query('select event_type from dabbir_ai_understanding_events where proposal_id=$1',[p.id]);assert.deepEqual(new Set(audit.rows.map(r=>r.event_type)),new Set(['PROPOSED','OWNER_APPROVED','REVOKED','ROLLBACK']));await db.exec('reset role');});
test('database: cross-tenant owner cannot read proposals or approve another tenant',async()=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claim.role','authenticated',false)",[otherOwner]);await db.exec('set role authenticated');assert.equal((await db.query('select * from dabbir_ai_knowledge_proposals where business_id=$1',[ids.business])).rows.length,0);await assert.rejects(rpc('dabbir_knowledge_review_v2',[ids.business,message,'approve']),/OWNER_REQUIRED/);await assert.rejects(rpc('dabbir_knowledge_propose_v2',[ids.other,null,null,'service','VIP',ids.service]),/KNOWLEDGE_TARGET_SCOPE_INVALID/);await db.exec('reset role');});
test('database: anonymous role cannot read proposal or event tables',async()=>{await db.exec('set role anon');await assert.rejects(db.query('select * from dabbir_ai_knowledge_proposals'),/permission denied/);await assert.rejects(db.query('select * from dabbir_ai_understanding_events'),/permission denied/);await db.exec('reset role');});
