import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const read=path=>readFile(new URL('../'+path,import.meta.url),'utf8');
const [brokerClient,bridge,actionBridge,supportBridge,teamBridge,copilot,diagnostic,logout,ui14,ui15,ui16,gateway,migration,searchMigration,supportMigration]=await Promise.all([
 read('api/_owner-broker-client.js'),read('api/owner-platform-bridge.js'),read('api/owner-action-bridge.js'),read('api/owner-support-bridge.js'),read('api/owner-team-bridge.js'),read('api/owner-platform-copilot.js'),read('api/owner-customer-diagnostic.js'),read('api/auth/owner-logout.js'),read('api/owner-command-center-v14.js'),read('api/owner-command-center-v15.js'),read('api/owner-command-center-v16.js'),read('api/owner-dashboard-gateway.js'),read('supabase/migrations/20260830102000_dabbir_platform_owner_action_bridge_v2.sql'),read('supabase/migrations/20260827155045_dabbir_platform_customer_search_escape_fix_v3.sql'),read('supabase/migrations/20260830112000_dabbir_platform_owner_support_summary_v1.sql')]);
test('owner broker client keeps owner session server-side and never exposes privileged credentials',()=>{assert.match(brokerClient,/__Host-dabbir_owner_session/);assert.match(brokerClient,/action:'owner_data'/);assert.match(brokerClient,/session_token/);assert.doesNotMatch(brokerClient,/SUPABASE_SERVICE_ROLE_KEY/);for(const f of [bridge,actionBridge,supportBridge,teamBridge,diagnostic,ui14,ui15,ui16])assert.doesNotMatch(f,/SUPABASE_SERVICE_ROLE_KEY/)});
test('owner platform bridge uses brokered reads and remains GET only',()=>{assert.match(bridge,/ownerBroker\(req,'platform_bridge'/);assert.match(bridge,/req\.method!=='GET'/);assert.match(bridge,/recognized_sales_aed/);assert.match(bridge,/operations_verified:true/);assert.doesNotMatch(bridge,/serviceKey|apikey:|authorization:`Bearer/)});
test('owner action bridge is explicitly allowlisted confirmed and brokered',()=>{assert.match(actionBridge,/requireSameOrigin/);assert.match(actionBridge,/confirmation!=='EXECUTE'/);assert.match(actionBridge,/ownerBroker\(req,'execute'/);assert.match(actionBridge,/ownerBroker\(req,'audit'/);for(const action of ['set_inventory','set_product_active','cancel_pending_order','set_service_active','support_create_case','support_add_note','support_set_status'])assert.match(actionBridge,new RegExp(action));assert.doesNotMatch(actionBridge,/create_expense|disconnect|set_member_role|access_token_ciphertext/)});
test('database action function remains service-role only and audited atomically',()=>{assert.match(migration,/security definer/);assert.match(migration,/grant execute[\s\S]*service_role/);assert.match(migration,/dabbir_platform_owner_audit/);assert.doesNotMatch(migration,/stripe|refund|create_expense|set_member_role/)});
test('customer search contract remains accounts plus businesses',()=>{assert.match(searchMigration,/jsonb_build_object\('accounts',v_result,'count',v_count\)/);assert.match(ui14,/Array\.isArray\(j\.accounts\)/);assert.match(ui14,/Array\.isArray\(x\.businesses\)/)});
test('unified owner command center has no legacy iframe or tenant-session dependency',()=>{assert.match(ui14,/v14-unified/);for(const hash of ['home','customers','operations','ai','governance','system'])assert.match(ui14,new RegExp(`id=\\"${hash}\\"`));assert.match(ui14,/owner-platform-bridge\?business_id/);assert.match(ui14,/owner-support-bridge\?customer_no/);assert.match(ui14,/owner-team-bridge\?business_id/);assert.match(ui14,/owner-platform-copilot/);assert.match(ui14,/owner-action-bridge/);assert.doesNotMatch(ui14,/<iframe/);assert.doesNotMatch(ui14,/\/api\/owner-operations\?business_id/);assert.match(ui15,/owner-command-center-v14\.js/);assert.match(ui16,/owner-command-center-v15\.js/);assert.match(gateway,/owner-command-center-v16\.js/)});
test('owner support and team reads are brokered and read-only',()=>{assert.match(supportBridge,/ownerBroker\(req,'support'/);assert.match(teamBridge,/ownerBroker\(req,'team'/);assert.match(teamBridge,/req\.method!=='GET'/);assert.doesNotMatch(teamBridge,/PATCH|set_member_role|employee_removed|employee_suspended/);assert.match(supportMigration,/security definer/);assert.match(supportMigration,/grant execute[\s\S]*service_role/)});
test('owner copilot remains same-origin owner-session gated and grounded',()=>{assert.match(copilot,/requireSameOrigin/);assert.match(copilot,/owner_session_verify/);assert.match(copilot,/generateDABBIRAiReply/);assert.match(copilot,/DETERMINISTIC_VERIFIED_FALLBACK/);assert.match(copilot,/FREE_TIER_ONLY/)});
test('customer diagnostic is deterministic read-only and brokered',()=>{assert.match(diagnostic,/ownerBroker\(req,'diagnostic_raw'/);for(const code of ['BILLING_INACTIVE','WHATSAPP_DEGRADED','OUT_OF_STOCK','PENDING_ORDERS','RECENT_OWNER_CHANGES'])assert.match(diagnostic,new RegExp(code));assert.match(diagnostic,/timeline/);assert.doesNotMatch(diagnostic,/method:'PATCH'|method:'DELETE'|dabbir_platform_owner_action_v1/);assert.match(ui15,/تشخيص العميل/);assert.match(ui15,/owner-customer-diagnostic\?customer_no/)});
test('v16 turns complaint into deterministic guided resolution without new mutation calls',()=>{for(const category of ['ACCESS','WHATSAPP','BILLING','INVENTORY','ORDERS','TEAM','DATA','TECHNICAL','GENERAL'])assert.match(ui16,new RegExp(category));assert.match(ui16,/استيعاب المشكلة/);assert.match(ui16,/مسار الحل/);assert.match(ui16,/رد قصير للعميل/);assert.match(ui16,/owner-customer-diagnostic\?customer_no/);assert.doesNotMatch(ui16,/fetch\(['"]\/api\/owner-action-bridge/);assert.doesNotMatch(ui16,/method:\s*['"](?:PATCH|DELETE|PUT)['"]/)});
test('owner logout clears owner cookie through same-origin POST',()=>{assert.match(logout,/requireSameOrigin/);assert.match(logout,/req\.method!=='POST'/);assert.match(logout,/Max-Age=0/)});
