import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {capabilityShadowVerdict} from '../api/_dabbir-capability-registry.js';
import {safeKnowledgeContext,mineProductionFailures} from '../api/_dabbir-intelligence-flywheel.js';
const migration=fs.readFileSync(new URL('../supabase/migrations/20260909030000_dabbir_intelligence_flywheel_v1.sql',import.meta.url),'utf8');

test('migration is additive, tenant private and eval cases contain no raw message body',()=>{assert.match(migration,/create extension if not exists vector with schema extensions/i);assert.match(migration,/embedding extensions\.vector\(768\)/i);assert.match(migration,/using hnsw/i);assert.match(migration,/using gin/i);assert.match(migration,/force row level security/ig);assert.match(migration,/revoke all on table public\.dabbir_ai_eval_cases from public, anon, authenticated/i);const block=migration.match(/create table if not exists public\.dabbir_ai_eval_cases \([\s\S]*?\n\);/i)?.[0]||'';assert.doesNotMatch(block,/\b(body|message_text|prompt|transcript)\b/i)});
test('failure miner is proposal-only and cannot auto-apply',()=>{assert.match(migration,/auto_apply',false/i);assert.match(migration,/status text not null default 'proposed'/i);assert.doesNotMatch(migration,/update\s+public\.dabbir_business_knowledge\s+set/i)});
test('failure miner safely parses historical metric drift instead of crashing on malformed JSON scalars',()=>{assert.match(migration,/char_length\(coalesce\(e\.metrics->>'operational_confidence',''\)\)<=32/i);assert.match(migration,/char_length\(coalesce\(metrics->>'semantic_confidence',''\)\)<=32/i);assert.match(migration,/lower\(coalesce\(metrics->>'voice',''\)\)='true'/i);assert.doesNotMatch(migration,/coalesce\(\(e\.metrics->>'operational_confidence'\)::numeric/i);assert.doesNotMatch(migration,/coalesce\(\(metrics->>'(?:semantic_confidence|operational_confidence)'\)::numeric/i);assert.doesNotMatch(migration,/\(metrics->>'voice'\)::boolean/i)});
test('capability registry starts shadow-only and cannot become execution authority from JS',()=>{const verdict=capabilityShadowVerdict({decision:{action:'CREATE_BOOKING'},capabilities:[{tool_name:'CREATE_BOOKING',enabled:true,risk_level:'MEDIUM',verification_mode:'DATABASE_READBACK'}]});assert.equal(verdict.mode,'SHADOW');assert.equal(verdict.would_block,false);const absent=capabilityShadowVerdict({decision:{action:'CANCEL_BOOKING'},capabilities:[]});assert.equal(absent.would_block,true)});
test('planner context truncates retrieved knowledge',()=>{const rows=safeKnowledgeContext([{knowledge_key:'x'.repeat(300),knowledge_type:'policy',content:'a'.repeat(3000),score:.9}]);assert.equal(rows[0].knowledge_key.length,180);assert.equal(rows[0].content.length,1200)});
test('production failure mining delegates to database without applying changes',async()=>{let args;const result=await mineProductionFailures({rpc:async(name,p)=>{args=[name,p];return {ok:true,auto_apply:false}},since:'48 hours'});assert.equal(args[0],'dabbir_ai_failure_mine_v1');assert.equal(result.auto_apply,false)});
