create table if not exists public.dabbir_user_numbers (
  user_id uuid primary key references auth.users(id) on delete cascade,
  serial_no bigint generated by default as identity (start with 100001 increment by 1),
  customer_no text generated always as ('DAB-' || serial_no::text) stored,
  created_at timestamptz not null default now(),
  constraint dabbir_user_numbers_serial_no_key unique (serial_no),
  constraint dabbir_user_numbers_customer_no_key unique (customer_no),
  constraint dabbir_user_numbers_customer_no_format check (customer_no ~ '^DAB-[0-9]{6,}$')
);

comment on table public.dabbir_user_numbers is 'Stable public-facing DABBIR account number. UUID remains canonical; customer_no is a support/display identifier only.';
comment on column public.dabbir_user_numbers.user_id is 'Canonical DABBIR auth.users UUID. Never expose as the primary human-facing support number.';
comment on column public.dabbir_user_numbers.customer_no is 'Stable human-facing DABBIR account number, e.g. DAB-100245. Never reassigned to another user.';

alter table public.dabbir_user_numbers enable row level security;

revoke all on table public.dabbir_user_numbers from anon;
revoke all on table public.dabbir_user_numbers from authenticated;
grant select on table public.dabbir_user_numbers to authenticated;

create policy dabbir_user_numbers_select_self
on public.dabbir_user_numbers
for select
to authenticated
using (user_id = auth.uid());

create or replace function public.dabbir_ensure_user_number(p_user_id uuid)
returns text
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_customer_no text;
begin
  if p_user_id is null then
    raise exception 'user_id_required';
  end if;

  if not exists (
    select 1
    from public.dabbir_memberships m
    where m.user_id = p_user_id
  ) then
    raise exception 'dabbir_membership_required';
  end if;

  insert into public.dabbir_user_numbers(user_id)
  values (p_user_id)
  on conflict (user_id) do nothing;

  select n.customer_no
    into v_customer_no
  from public.dabbir_user_numbers n
  where n.user_id = p_user_id;

  return v_customer_no;
end;
$$;

revoke all on function public.dabbir_ensure_user_number(uuid) from public, anon, authenticated;

create or replace function public.dabbir_assign_user_number_on_membership()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  perform public.dabbir_ensure_user_number(new.user_id);
  return new;
end;
$$;

revoke all on function public.dabbir_assign_user_number_on_membership() from public, anon, authenticated;

drop trigger if exists trg_dabbir_assign_user_number_on_membership on public.dabbir_memberships;
create trigger trg_dabbir_assign_user_number_on_membership
after insert on public.dabbir_memberships
for each row execute function public.dabbir_assign_user_number_on_membership();

insert into public.dabbir_user_numbers(user_id)
select x.user_id
from (
  select m.user_id, min(m.created_at) as first_membership_at
  from public.dabbir_memberships m
  group by m.user_id
) x
left join public.dabbir_user_numbers n on n.user_id = x.user_id
where n.user_id is null
order by x.first_membership_at, x.user_id
on conflict (user_id) do nothing;

create or replace function public.dabbir_my_customer_no()
returns text
language sql
stable
security definer
set search_path = public, auth
as $$
  select n.customer_no
  from public.dabbir_user_numbers n
  where n.user_id = auth.uid();
$$;

grant execute on function public.dabbir_my_customer_no() to authenticated;
revoke execute on function public.dabbir_my_customer_no() from anon;

create or replace function public.dabbir_resolve_customer_no(p_customer_no text)
returns table (
  user_id uuid,
  customer_no text,
  business_ids uuid[]
)
language sql
stable
security definer
set search_path = public, auth
as $$
  select
    n.user_id,
    n.customer_no,
    coalesce(array_agg(distinct m.business_id) filter (where m.business_id is not null), '{}'::uuid[])
  from public.dabbir_user_numbers n
  left join public.dabbir_memberships m on m.user_id = n.user_id
  where n.customer_no = upper(trim(p_customer_no))
  group by n.user_id, n.customer_no;
$$;

revoke all on function public.dabbir_resolve_customer_no(text) from public, anon, authenticated;

create or replace function public.dabbir_support_resolve_account(p_query text)
returns table (
  user_id uuid,
  customer_no text,
  matched_on text,
  business_ids uuid[]
)
language sql
stable
security definer
set search_path = public, auth
as $$
  with q as (
    select nullif(trim(p_query), '') as raw,
           upper(nullif(trim(p_query), '')) as upper_value,
           lower(nullif(trim(p_query), '')) as lower_value,
           regexp_replace(coalesce(p_query, ''), '[^0-9+]', '', 'g') as phone_value
  ), candidates as (
    select
      n.user_id,
      n.customer_no,
      case
        when n.customer_no = q.upper_value then 'customer_no'
        when lower(u.email) = q.lower_value then 'email'
        when regexp_replace(coalesce(u.phone, ''), '[^0-9+]', '', 'g') = q.phone_value and q.phone_value <> '' then 'phone'
        else null
      end as matched_on
    from public.dabbir_user_numbers n
    join auth.users u on u.id = n.user_id
    cross join q
    where q.raw is not null
      and (
        n.customer_no = q.upper_value
        or lower(u.email) = q.lower_value
        or (q.phone_value <> '' and regexp_replace(coalesce(u.phone, ''), '[^0-9+]', '', 'g') = q.phone_value)
      )
  )
  select
    c.user_id,
    c.customer_no,
    c.matched_on,
    coalesce(array_agg(distinct m.business_id) filter (where m.business_id is not null), '{}'::uuid[])
  from candidates c
  left join public.dabbir_memberships m on m.user_id = c.user_id
  group by c.user_id, c.customer_no, c.matched_on
  order by c.customer_no;
$$;

revoke all on function public.dabbir_support_resolve_account(text) from public, anon, authenticated;
