-- DABBIR platform P&L ledger v1.
-- Tracks DABBIR's own revenue/costs only. Tenant/customer operational money is excluded.
-- Owner labor is intentionally excluded while DABBIR is operated by the solo owner.

create table if not exists dabbir_private.platform_finance_events (
  id bigint generated by default as identity primary key,
  source_event_key text not null unique,
  direction text not null check (direction in ('COST','REVENUE')),
  category text not null check (category in (
    'AI','WHATSAPP','HOSTING','DATABASE','STORAGE','MONITORING','INTEGRATION','MAPS',
    'APP_STORE_FEE','PAYMENT_FEE','DOMAIN','LEGAL','MARKETING','LABOR','OTHER',
    'SUBSCRIPTION_REVENUE','OTHER_REVENUE'
  )),
  provider text not null,
  business_id uuid references public.dabbir_businesses(id) on delete set null,
  amount numeric(20,6) not null check (amount >= 0),
  currency text not null check (currency ~ '^[A-Z]{3}$'),
  amount_aed numeric(20,6) not null check (amount_aed >= 0),
  authority text not null check (authority in (
    'PROVIDER_RECONCILED','PROVIDER_REPORTED','METERED_ACTUAL','MANUAL_VERIFIED','ESTIMATED'
  )),
  occurred_at timestamptz not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  check (char_length(source_event_key) between 3 and 240),
  check (char_length(provider) between 1 and 120)
);

create index if not exists platform_finance_events_month_idx
  on dabbir_private.platform_finance_events (occurred_at desc);
create index if not exists platform_finance_events_business_month_idx
  on dabbir_private.platform_finance_events (business_id, occurred_at desc)
  where business_id is not null;
create index if not exists platform_finance_events_category_month_idx
  on dabbir_private.platform_finance_events (category, occurred_at desc);

alter table dabbir_private.platform_finance_events enable row level security;
alter table dabbir_private.platform_finance_events force row level security;
revoke all on dabbir_private.platform_finance_events from public, anon, authenticated;
revoke update, delete, truncate on dabbir_private.platform_finance_events from service_role;
grant select, insert on dabbir_private.platform_finance_events to service_role;

create table if not exists dabbir_private.platform_finance_sources (
  source_key text primary key,
  provider text not null,
  category text not null,
  capture_mode text not null check (capture_mode in ('AUTO_DERIVED','PROVIDER_SYNC','MANUAL_VERIFIED')),
  coverage_state text not null default 'UNCONFIRMED' check (coverage_state in ('AUTO','SYNCED','FREE','NOT_USED','UNCONFIRMED')),
  required_for_complete boolean not null default true,
  active boolean not null default true,
  note text,
  updated_at timestamptz not null default now(),
  check (char_length(source_key) between 3 and 120),
  check (char_length(provider) between 1 and 120)
);

alter table dabbir_private.platform_finance_sources enable row level security;
alter table dabbir_private.platform_finance_sources force row level security;
revoke all on dabbir_private.platform_finance_sources from public, anon, authenticated;
grant select, insert, update on dabbir_private.platform_finance_sources to service_role;

insert into dabbir_private.platform_finance_sources(source_key,provider,category,capture_mode,coverage_state,required_for_complete,active,note)
values
  ('ai_usage_meter','DABBIR AI meter','AI','AUTO_DERIVED','AUTO',true,true,'AI is derived from the authoritative DABBIR AI metering and reconciliation views.'),
  ('vercel_infrastructure','Vercel','HOSTING','PROVIDER_SYNC','UNCONFIRMED',true,true,'Hosting/runtime/platform bill.'),
  ('supabase_infrastructure','Supabase','DATABASE','PROVIDER_SYNC','UNCONFIRMED',true,true,'Database, storage, compute and network bill.'),
  ('meta_whatsapp','Meta WhatsApp','WHATSAPP','PROVIDER_SYNC','UNCONFIRMED',false,true,'Required dynamically whenever WhatsApp traffic exists in the period.'),
  ('sentry_monitoring','Sentry','MONITORING','PROVIDER_SYNC','UNCONFIRMED',true,true,'Monitoring/error tracking cost or verified free tier.'),
  ('composio_integration','Composio','INTEGRATION','PROVIDER_SYNC','UNCONFIRMED',true,true,'Integration platform cost or verified free tier.'),
  ('google_maps','Google Maps','MAPS','PROVIDER_SYNC','UNCONFIRMED',false,true,'Optional until map/routing billing is activated.'),
  ('apple_store_fee','Apple','APP_STORE_FEE','PROVIDER_SYNC','UNCONFIRMED',false,true,'Required dynamically when Apple production subscription revenue exists.'),
  ('google_play_fee','Google Play','APP_STORE_FEE','PROVIDER_SYNC','UNCONFIRMED',false,true,'Required dynamically when Google production subscription revenue exists.'),
  ('web_payment_fee','Web billing provider','PAYMENT_FEE','PROVIDER_SYNC','UNCONFIRMED',false,true,'Required dynamically when live web subscription revenue exists.')
on conflict (source_key) do nothing;

create or replace function public.dabbir_platform_finance_record_event_v1(
  p_source_event_key text,
  p_direction text,
  p_category text,
  p_provider text,
  p_business_id uuid,
  p_amount numeric,
  p_currency text,
  p_amount_aed numeric,
  p_authority text,
  p_occurred_at timestamptz,
  p_metadata jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path to 'pg_catalog','public','dabbir_private'
as $function$
declare
  v_id bigint;
  v_existing dabbir_private.platform_finance_events%rowtype;
begin
  if p_source_event_key is null or char_length(trim(p_source_event_key)) not between 3 and 240 then
    raise exception 'DABBIR_FINANCE_SOURCE_KEY_INVALID';
  end if;
  if p_direction not in ('COST','REVENUE') then raise exception 'DABBIR_FINANCE_DIRECTION_INVALID'; end if;
  if p_category not in ('AI','WHATSAPP','HOSTING','DATABASE','STORAGE','MONITORING','INTEGRATION','MAPS','APP_STORE_FEE','PAYMENT_FEE','DOMAIN','LEGAL','MARKETING','LABOR','OTHER','SUBSCRIPTION_REVENUE','OTHER_REVENUE') then
    raise exception 'DABBIR_FINANCE_CATEGORY_INVALID';
  end if;
  if p_provider is null or char_length(trim(p_provider)) not between 1 and 120 then raise exception 'DABBIR_FINANCE_PROVIDER_INVALID'; end if;
  if p_amount is null or p_amount < 0 or p_amount_aed is null or p_amount_aed < 0 then raise exception 'DABBIR_FINANCE_AMOUNT_INVALID'; end if;
  if upper(coalesce(p_currency,'')) !~ '^[A-Z]{3}$' then raise exception 'DABBIR_FINANCE_CURRENCY_INVALID'; end if;
  if p_authority not in ('PROVIDER_RECONCILED','PROVIDER_REPORTED','METERED_ACTUAL','MANUAL_VERIFIED','ESTIMATED') then raise exception 'DABBIR_FINANCE_AUTHORITY_INVALID'; end if;
  if p_occurred_at is null or p_occurred_at > now() + interval '5 minutes' then raise exception 'DABBIR_FINANCE_OCCURRED_AT_INVALID'; end if;
  if p_business_id is not null and not exists(select 1 from public.dabbir_businesses b where b.id=p_business_id) then raise exception 'DABBIR_FINANCE_BUSINESS_NOT_FOUND'; end if;

  select * into v_existing from dabbir_private.platform_finance_events where source_event_key=trim(p_source_event_key);
  if found then
    if v_existing.direction<>p_direction
      or v_existing.category<>p_category
      or v_existing.provider<>trim(p_provider)
      or v_existing.business_id is distinct from p_business_id
      or v_existing.amount<>p_amount
      or v_existing.currency<>upper(p_currency)
      or v_existing.amount_aed<>p_amount_aed
      or v_existing.authority<>p_authority
      or v_existing.occurred_at<>p_occurred_at then
      raise exception 'DABBIR_FINANCE_EVENT_CONFLICT';
    end if;
    return v_existing.id;
  end if;

  insert into dabbir_private.platform_finance_events(
    source_event_key,direction,category,provider,business_id,amount,currency,amount_aed,authority,occurred_at,metadata
  ) values (
    trim(p_source_event_key),p_direction,p_category,trim(p_provider),p_business_id,p_amount,upper(p_currency),p_amount_aed,p_authority,p_occurred_at,coalesce(p_metadata,'{}'::jsonb)
  ) returning id into v_id;
  return v_id;
end;
$function$;

create or replace function public.dabbir_platform_pnl_month_v1(p_month date default null)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog','public','dabbir_private'
as $function$
declare
  v_month_start timestamptz:=date_trunc('month',coalesce(p_month,current_date)::timestamptz);
  v_month_end timestamptz:=date_trunc('month',coalesce(p_month,current_date)::timestamptz)+interval '1 month';
  v_generated timestamptz:=now();
  v_ai_cost numeric:=0;
  v_ai_requests bigint:=0;
  v_ai_unpriced bigint:=0;
  v_ai_pending bigint:=0;
  v_other_cost numeric:=0;
  v_revenue numeric:=0;
  v_whatsapp_messages bigint:=0;
  v_live_web boolean:=false;
  v_live_apple boolean:=false;
  v_live_google boolean:=false;
  v_missing jsonb:='[]'::jsonb;
  v_complete boolean:=false;
  v_active_businesses bigint:=0;
  v_shared_cost numeric:=0;
  v_result jsonb;
begin
  if p_month is not null and (p_month < date '2020-01-01' or p_month > current_date + interval '1 month') then
    raise exception 'DABBIR_PNL_MONTH_INVALID';
  end if;

  select
    coalesce(sum(v.known_cost_aed),0),
    coalesce(sum(v.ai_requests),0)::bigint,
    coalesce(sum(v.unpriced_operations),0)::bigint,
    count(*) filter(where v.cost_authority='PENDING_GATEWAY_RECONCILIATION')::bigint
  into v_ai_cost,v_ai_requests,v_ai_unpriced,v_ai_pending
  from public.dabbir_ai_customer_cost_monthly_v1 v
  where v.month_start=v_month_start;

  select
    coalesce(sum(e.amount_aed) filter(where e.direction='COST'),0),
    coalesce(sum(e.amount_aed) filter(where e.direction='REVENUE'),0),
    coalesce(sum(e.amount_aed) filter(where e.direction='COST' and e.business_id is null),0)
  into v_other_cost,v_revenue,v_shared_cost
  from dabbir_private.platform_finance_events e
  where e.occurred_at>=v_month_start and e.occurred_at<v_month_end;

  select count(*)::bigint into v_whatsapp_messages
  from public.dabbir_messages m
  join public.dabbir_conversations c on c.id=m.conversation_id
  where m.created_at>=v_month_start and m.created_at<v_month_end and c.channel_type='whatsapp';

  select exists(select 1 from public.dabbir_stripe_events where livemode=true and stripe_created_at>=v_month_start and stripe_created_at<v_month_end) into v_live_web;
  select exists(select 1 from public.dabbir_apple_entitlements where lower(coalesce(environment,''))='production' and coalesce(purchased_at,verified_at)>=v_month_start and coalesce(purchased_at,verified_at)<v_month_end) into v_live_apple;
  select exists(select 1 from public.dabbir_google_entitlements where lower(coalesce(environment,''))='production' and coalesce(start_at,verified_at)>=v_month_start and coalesce(start_at,verified_at)<v_month_end) into v_live_google;

  with required_sources as (
    select source_key,provider,category,coverage_state
    from dabbir_private.platform_finance_sources
    where active and required_for_complete
    union all
    select source_key,provider,category,coverage_state from dabbir_private.platform_finance_sources where source_key='meta_whatsapp' and active and v_whatsapp_messages>0
    union all
    select source_key,provider,category,coverage_state from dabbir_private.platform_finance_sources where source_key='apple_store_fee' and active and v_live_apple
    union all
    select source_key,provider,category,coverage_state from dabbir_private.platform_finance_sources where source_key='google_play_fee' and active and v_live_google
    union all
    select source_key,provider,category,coverage_state from dabbir_private.platform_finance_sources where source_key='web_payment_fee' and active and v_live_web
  ), distinct_required as (
    select distinct on(source_key) source_key,provider,category,coverage_state from required_sources order by source_key
  ), missing as (
    select r.*
    from distinct_required r
    where r.source_key<>'ai_usage_meter'
      and r.coverage_state not in ('FREE','NOT_USED')
      and not exists(
        select 1 from dabbir_private.platform_finance_events e
        where e.occurred_at>=v_month_start and e.occurred_at<v_month_end
          and (
            (r.source_key='vercel_infrastructure' and e.direction='COST' and e.provider ilike 'Vercel%') or
            (r.source_key='supabase_infrastructure' and e.direction='COST' and e.provider ilike 'Supabase%') or
            (r.source_key='meta_whatsapp' and e.direction='COST' and e.category='WHATSAPP') or
            (r.source_key='sentry_monitoring' and e.direction='COST' and e.provider ilike 'Sentry%') or
            (r.source_key='composio_integration' and e.direction='COST' and e.provider ilike 'Composio%') or
            (r.source_key='apple_store_fee' and e.direction='COST' and e.category='APP_STORE_FEE' and e.provider ilike 'Apple%') or
            (r.source_key='google_play_fee' and e.direction='COST' and e.category='APP_STORE_FEE' and e.provider ilike 'Google%') or
            (r.source_key='web_payment_fee' and e.direction='COST' and e.category='PAYMENT_FEE')
          )
      )
  )
  select coalesce(jsonb_agg(jsonb_build_object('source_key',source_key,'provider',provider,'category',category,'state',coverage_state) order by source_key),'[]'::jsonb)
  into v_missing from missing;

  if v_ai_unpriced>0 or v_ai_pending>0 then
    v_missing:=v_missing || jsonb_build_array(jsonb_build_object(
      'source_key','ai_usage_meter','provider','DABBIR AI meter','category','AI','state',
      case when v_ai_pending>0 then 'PENDING_RECONCILIATION' else 'UNPRICED_OPERATIONS' end
    ));
  end if;
  if (v_live_web or v_live_apple or v_live_google) and not exists(
    select 1 from dabbir_private.platform_finance_events e where e.direction='REVENUE' and e.occurred_at>=v_month_start and e.occurred_at<v_month_end
  ) then
    v_missing:=v_missing || jsonb_build_array(jsonb_build_object('source_key','subscription_revenue','provider','Subscription providers','category','SUBSCRIPTION_REVENUE','state','LIVE_REVENUE_NOT_CAPTURED'));
  end if;

  v_complete=jsonb_array_length(v_missing)=0;

  with used_businesses as (
    select distinct v.business_id from public.dabbir_ai_customer_cost_monthly_v1 v where v.month_start=v_month_start and v.business_id is not null
    union
    select distinct m.business_id from public.dabbir_messages m where m.created_at>=v_month_start and m.created_at<v_month_end and m.business_id is not null
    union
    select distinct e.business_id from dabbir_private.platform_finance_events e where e.occurred_at>=v_month_start and e.occurred_at<v_month_end and e.business_id is not null
  ) select count(*)::bigint into v_active_businesses from used_businesses;

  with ai_business as (
    select v.business_id,round(coalesce(sum(v.known_cost_aed),0),6) ai_cost_aed,coalesce(sum(v.unpriced_operations),0)::bigint unpriced
    from public.dabbir_ai_customer_cost_monthly_v1 v where v.month_start=v_month_start group by v.business_id
  ), ledger_business as (
    select e.business_id,
      round(coalesce(sum(e.amount_aed) filter(where e.direction='REVENUE'),0),6) revenue_aed,
      round(coalesce(sum(e.amount_aed) filter(where e.direction='COST'),0),6) direct_other_cost_aed
    from dabbir_private.platform_finance_events e
    where e.occurred_at>=v_month_start and e.occurred_at<v_month_end and e.business_id is not null
    group by e.business_id
  ), used as (
    select business_id from ai_business where business_id is not null
    union select business_id from ledger_business where business_id is not null
    union select distinct m.business_id from public.dabbir_messages m where m.created_at>=v_month_start and m.created_at<v_month_end and m.business_id is not null
  ), rows as (
    select b.id,b.name,
      coalesce(l.revenue_aed,0) revenue_aed,
      coalesce(a.ai_cost_aed,0) ai_cost_aed,
      coalesce(l.direct_other_cost_aed,0) direct_other_cost_aed,
      case when v_active_businesses>0 then round(v_shared_cost/v_active_businesses,6) else 0 end allocated_shared_cost_aed,
      round(coalesce(l.revenue_aed,0)-coalesce(a.ai_cost_aed,0)-coalesce(l.direct_other_cost_aed,0)-case when v_active_businesses>0 then v_shared_cost/v_active_businesses else 0 end,6) known_contribution_aed,
      coalesce(a.unpriced,0)::bigint unpriced_ai_operations
    from used u join public.dabbir_businesses b on b.id=u.business_id
    left join ai_business a on a.business_id=b.id
    left join ledger_business l on l.business_id=b.id
  )
  select jsonb_build_object(
    'generated_at',v_generated,
    'month_start',v_month_start,
    'month_end',v_month_end,
    'accounting_scope','DABBIR_PLATFORM_ONLY',
    'owner_labor_state','EXCLUDED_SOLO_OWNER',
    'revenue',jsonb_build_object(
      'known_aed',round(v_revenue,6),
      'live_web_evidence',v_live_web,
      'live_apple_evidence',v_live_apple,
      'live_google_evidence',v_live_google
    ),
    'costs',jsonb_build_object(
      'ai_known_aed',round(v_ai_cost,6),
      'other_known_aed',round(v_other_cost,6),
      'total_known_aed',round(v_ai_cost+v_other_cost,6),
      'shared_known_aed',round(v_shared_cost,6),
      'ai_requests',v_ai_requests,
      'unpriced_ai_operations',v_ai_unpriced,
      'pending_ai_reconciliations',v_ai_pending,
      'whatsapp_messages',v_whatsapp_messages
    ),
    'known_operating_result_aed',round(v_revenue-v_ai_cost-v_other_cost,6),
    'net_profit_aed',case when v_complete then round(v_revenue-v_ai_cost-v_other_cost,6) else null end,
    'measurement_state',case when v_complete then 'COMPLETE' else 'PARTIAL' end,
    'missing_sources',v_missing,
    'active_businesses',v_active_businesses,
    'by_category',(
      with c as (
        select 'AI'::text category,round(v_ai_cost,6) amount_aed
        union all
        select e.category,round(sum(e.amount_aed),6) from dabbir_private.platform_finance_events e
        where e.direction='COST' and e.occurred_at>=v_month_start and e.occurred_at<v_month_end group by e.category
      ) select coalesce(jsonb_agg(jsonb_build_object('category',category,'amount_aed',amount_aed) order by amount_aed desc),'[]'::jsonb) from c where amount_aed<>0
    ),
    'by_provider',(
      with p as (
        select v.provider,round(sum(v.known_cost_aed),6) amount_aed from public.dabbir_ai_customer_cost_monthly_v1 v where v.month_start=v_month_start group by v.provider
        union all
        select e.provider,round(sum(e.amount_aed),6) from dabbir_private.platform_finance_events e where e.direction='COST' and e.occurred_at>=v_month_start and e.occurred_at<v_month_end group by e.provider
      ), g as (select provider,round(sum(amount_aed),6) amount_aed from p group by provider)
      select coalesce(jsonb_agg(jsonb_build_object('provider',provider,'amount_aed',amount_aed) order by amount_aed desc),'[]'::jsonb) from g where amount_aed<>0
    ),
    'businesses',coalesce((select jsonb_agg(jsonb_build_object(
      'business_id',id,'name',name,'revenue_aed',revenue_aed,'ai_cost_aed',ai_cost_aed,
      'direct_other_cost_aed',direct_other_cost_aed,'allocated_shared_cost_aed',allocated_shared_cost_aed,
      'known_contribution_aed',known_contribution_aed,'unpriced_ai_operations',unpriced_ai_operations
    ) order by known_contribution_aed asc,name) from rows),'[]'::jsonb)
  ) into v_result;

  return v_result;
end;
$function$;

revoke all on function public.dabbir_platform_finance_record_event_v1(text,text,text,text,uuid,numeric,text,numeric,text,timestamptz,jsonb) from public,anon,authenticated;
grant execute on function public.dabbir_platform_finance_record_event_v1(text,text,text,text,uuid,numeric,text,numeric,text,timestamptz,jsonb) to service_role;
revoke all on function public.dabbir_platform_pnl_month_v1(date) from public,anon,authenticated;
grant execute on function public.dabbir_platform_pnl_month_v1(date) to service_role;
