import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2.112.2";
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});
const enc=new TextEncoder();
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const BASE_PLAN='owner_monthly_v1',BUSINESS_PLAN='owner_extra_business_v1',BRANCH_PLAN='owner_extra_branch_v1';
const BASE_MINOR=3999,BUSINESS_MINOR=2999,BRANCH_MINOR=1999,TRIAL_DAYS=14,CURRENCY='aed',INTERVAL='month';
const PLAN_CODES=[BASE_PLAN,BUSINESS_PLAN,BRANCH_PLAN];
function hex(buf:ArrayBuffer){return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function verify(raw:string,header:string,secret:string){const parts=header.split(',').map(x=>x.trim());const t=parts.find(x=>x.startsWith('t='))?.slice(2);const sigs=parts.filter(x=>x.startsWith('v1=')).map(x=>x.slice(3));if(!t||!sigs.length)return false;const ts=Number(t);if(!Number.isFinite(ts)||Math.abs(Date.now()/1000-ts)>300)return false;const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const signed=await crypto.subtle.sign('HMAC',key,enc.encode(`${t}.${raw}`));const expected=hex(signed);return sigs.some(s=>s===expected)}
function safeBusinessId(value:any){const id=String(value||'');return UUID_RE.test(id)?id:null}
function objectId(value:any){if(!value)return null;return typeof value==='string'?value:typeof value?.id==='string'?value.id:null}
function unixIso(value:any){const seconds=Number(value||0);return Number.isFinite(seconds)&&seconds>0?new Date(seconds*1000).toISOString():null}
function sandboxSecret(){const key=String(Deno.env.get('STRIPE_SECRET_KEY')||'');if(!key)throw new Error('STRIPE_SECRET_KEY_MISSING');if(key.startsWith('sk_live_'))throw new Error('LIVE_BILLING_DISABLED');if(!key.startsWith('sk_test_'))throw new Error('INVALID_STRIPE_SANDBOX_KEY');return key}
async function stripeGet(path:string){const r=await fetch(`https://api.stripe.com/v1${path}`,{headers:{Authorization:`Bearer ${sandboxSecret()}`,'Stripe-Version':'2026-06-24.preview'}});const text=await r.text();let data:any={};try{data=JSON.parse(text)}catch{}if(!r.ok)throw new Error(String(data?.error?.code||data?.error?.message||'STRIPE_REQUEST_FAILED').slice(0,120));if(data?.livemode===true)throw new Error('LIVE_BILLING_DISABLED');return data}
function isDabbirMetadata(value:any){return String(value?.metadata?.app||'').toLowerCase()==='dabbir'&&String(value?.metadata?.plan||'').toLowerCase()==='owner'&&String(value?.metadata?.plan_code||'')===BASE_PLAN}
async function billingPlans(){const {data,error}=await db.from('dabbir_billing_plans').select('plan_code,amount_minor,currency,interval,trial_days,stripe_test_price_id,active').in('plan_code',PLAN_CODES).eq('active',true);if(error||!Array.isArray(data))throw new Error('BILLING_PLAN_NOT_CONFIGURED');const map=new Map(data.map((row:any)=>[String(row.plan_code),row]));const expected:any={
 [BASE_PLAN]:{amount:BASE_MINOR,trial:TRIAL_DAYS},[BUSINESS_PLAN]:{amount:BUSINESS_MINOR,trial:0},[BRANCH_PLAN]:{amount:BRANCH_MINOR,trial:0}
};for(const code of PLAN_CODES){const row:any=map.get(code);if(!row)throw new Error('BILLING_PLAN_NOT_CONFIGURED');if(Number(row.amount_minor)!==expected[code].amount||String(row.currency||'').toLowerCase()!==CURRENCY||String(row.interval||'')!==INTERVAL||Number(row.trial_days)!==expected[code].trial)throw new Error('BILLING_PLAN_CONTRACT_MISMATCH');const priceId=String(row.stripe_test_price_id||'');if(!/^price_[A-Za-z0-9]+$/.test(priceId))throw new Error('BILLING_PRICE_NOT_CONFIGURED');row.stripe_test_price_id=priceId;}return map;}
async function alreadyProcessed(eventId:string){const {data,error}=await db.from('dabbir_stripe_events').select('stripe_event_id').eq('stripe_event_id',eventId).eq('status','processed').limit(1);if(error)throw error;return Boolean(data?.length)}
async function recordDabbirEvent(evt:any,status:'processed'|'failed',errorCode:string|null=null){const {error}=await db.from('dabbir_stripe_events').upsert({stripe_event_id:String(evt.id),event_type:String(evt.type),livemode:Boolean(evt.livemode),stripe_created_at:unixIso(evt.created),status,error_code:errorCode?String(errorCode).slice(0,120):null,attempt_count:1,processed_at:status==='processed'?new Date().toISOString():null,updated_at:new Date().toISOString()},{onConflict:'stripe_event_id'});if(error)throw error}
async function validateItems(subscription:any){const plans=await billingPlans();const byPrice=new Map([...plans.entries()].map(([code,row]:any)=>[String(row.stripe_test_price_id),code]));const quantities:any={[BASE_PLAN]:0,[BUSINESS_PLAN]:0,[BRANCH_PLAN]:0};const items=Array.isArray(subscription?.items?.data)?subscription.items.data:[];if(!items.length)throw new Error('DABBIR_SUBSCRIPTION_ITEMS_MISSING');for(const item of items){const priceId=objectId(item?.price);const code=priceId?byPrice.get(priceId):null;if(!code)throw new Error('DABBIR_SUBSCRIPTION_PRICE_MISMATCH');const quantity=Math.max(0,Number(item?.quantity||0));if(!Number.isInteger(quantity)||quantity<1)throw new Error('DABBIR_SUBSCRIPTION_QUANTITY_INVALID');if(quantities[code]!==0)throw new Error('DABBIR_SUBSCRIPTION_DUPLICATE_PLAN');quantities[code]=quantity;}if(quantities[BASE_PLAN]!==1)throw new Error('DABBIR_BASE_PLAN_REQUIRED');const extraBusinesses=quantities[BUSINESS_PLAN]||0,extraBranches=quantities[BRANCH_PLAN]||0;const totalMinor=BASE_MINOR+(extraBusinesses*BUSINESS_MINOR)+(extraBranches*BRANCH_MINOR);const metadata=subscription?.metadata||{};if(Number(metadata.additional_businesses||0)!==extraBusinesses||Number(metadata.additional_branches||0)!==extraBranches||Number(metadata.monthly_amount_minor||totalMinor)!==totalMinor)throw new Error('DABBIR_PRICING_METADATA_MISMATCH');return {plans,quantities,extraBusinesses,extraBranches,totalMinor};}
async function saveSubscription(subscription:any,fallbackBusinessId:string|null=null){if(subscription?.livemode===true)throw new Error('LIVE_BILLING_DISABLED');const businessId=safeBusinessId(subscription?.metadata?.billing_root_business_id||subscription?.metadata?.business_id||fallbackBusinessId);if(!businessId||!isDabbirMetadata(subscription))throw new Error('DABBIR_SUBSCRIPTION_METADATA_INVALID');const pricing=await validateItems(subscription);const base:any=pricing.plans.get(BASE_PLAN);const item=subscription?.items?.data?.find((x:any)=>objectId(x?.price)===base.stripe_test_price_id)||subscription?.items?.data?.[0]||null;const row={business_id:businessId,stripe_customer_id:objectId(subscription.customer),stripe_subscription_id:String(subscription.id||''),stripe_price_id:base.stripe_test_price_id,status:String(subscription.status||'unknown'),trial_started_at:unixIso(subscription.trial_start),trial_ends_at:unixIso(subscription.trial_end),current_period_ends_at:unixIso(subscription.current_period_end||item?.current_period_end),cancel_at_period_end:Boolean(subscription.cancel_at_period_end),canceled_at:unixIso(subscription.canceled_at),latest_invoice_id:objectId(subscription.latest_invoice),additional_businesses:pricing.extraBusinesses,additional_branches:pricing.extraBranches,monthly_amount_minor:pricing.totalMinor,pricing_snapshot:{base_minor:BASE_MINOR,additional_business_minor:BUSINESS_MINOR,additional_branch_minor:BRANCH_MINOR,additional_businesses:pricing.extraBusinesses,additional_branches:pricing.extraBranches,total_minor:pricing.totalMinor,currency:'AED',interval:'month'},stripe_updated_at:new Date().toISOString(),updated_at:new Date().toISOString()};const {error}=await db.from('dabbir_billing_accounts').upsert(row,{onConflict:'business_id'});if(error)throw error;return row}
function invoiceSubscriptionId(invoice:any){return objectId(invoice?.subscription)||objectId(invoice?.parent?.subscription_details?.subscription)}
async function classifyDabbir(evt:any){const obj=evt?.data?.object||{};if((evt.type==='checkout.session.completed'||evt.type==='checkout.session.async_payment_succeeded')&&isDabbirMetadata(obj))return {yes:true,obj,subscription:null};if(String(evt.type||'').startsWith('customer.subscription.')&&isDabbirMetadata(obj))return {yes:true,obj,subscription:obj};if(evt.type==='invoice.paid'||evt.type==='invoice.payment_failed'){if(evt.livemode===true)return {yes:false,obj,subscription:null};const id=invoiceSubscriptionId(obj);if(!id)return {yes:false,obj,subscription:null};const subscription=await stripeGet(`/subscriptions/${encodeURIComponent(id)}`);return {yes:isDabbirMetadata(subscription),obj,subscription}}return {yes:false,obj,subscription:null}}
async function processDabbir(evt:any,classification:any){if(evt.livemode===true)throw new Error('LIVE_BILLING_DISABLED');if(await alreadyProcessed(String(evt.id)))return;const obj=classification.obj;if(evt.type==='checkout.session.completed'||evt.type==='checkout.session.async_payment_succeeded'){const businessId=safeBusinessId(obj.client_reference_id||obj.metadata?.billing_root_business_id||obj.metadata?.business_id);const subscriptionId=objectId(obj.subscription);if(!businessId||!subscriptionId)throw new Error('CHECKOUT_SUBSCRIPTION_METADATA_MISSING');const subscription=await stripeGet(`/subscriptions/${encodeURIComponent(subscriptionId)}`);await saveSubscription(subscription,businessId)}else if(String(evt.type||'').startsWith('customer.subscription.')){await saveSubscription(obj)}else if(evt.type==='invoice.paid'||evt.type==='invoice.payment_failed'){const subscription=classification.subscription;if(!subscription)throw new Error('INVOICE_SUBSCRIPTION_MISSING');const row=await saveSubscription(subscription);const {error}=await db.from('dabbir_billing_accounts').update({latest_invoice_id:String(obj.id||''),last_invoice_status:evt.type==='invoice.paid'?'paid':'payment_failed',stripe_updated_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('business_id',row.business_id);if(error)throw error}await recordDabbirEvent(evt,'processed')}

Deno.serve(async(req:Request)=>{
 if(req.method!=='POST')return new Response('method not allowed',{status:405});
 const secret=Deno.env.get('STRIPE_WEBHOOK_SECRET');if(!secret)return new Response('webhook secret missing',{status:503});
 const raw=await req.text();const sig=req.headers.get('stripe-signature')||'';if(!(await verify(raw,sig,secret)))return new Response('invalid signature',{status:401});
 let evt:any;try{evt=JSON.parse(raw)}catch{return new Response('invalid json',{status:400})}
 let classification:any={yes:false,obj:evt?.data?.object||{},subscription:null};
 try{classification=await classifyDabbir(evt);if(classification.yes){try{await processDabbir(evt,classification);return new Response(JSON.stringify({received:true,dabbir:true}),{status:200,headers:{'content-type':'application/json'}})}catch(e){await recordDabbirEvent(evt,'failed',String((e as Error)?.message||'DABBIR_WEBHOOK_FAILED')).catch(()=>{});return new Response('processing failed',{status:500})}}
  const obj=evt?.data?.object||{};
  if(evt.type==='checkout.session.completed'||evt.type==='checkout.session.async_payment_succeeded'){
    const amount=Number(obj.amount_total||0)/100;const state=obj.payment_status==='paid'?'paid':String(obj.payment_status||'pending');await db.rpc('barman_record_stripe_checkout',{p_session_id:String(obj.id),p_payment_intent_id:obj.payment_intent?String(obj.payment_intent):null,p_customer_id:obj.customer?String(obj.customer):null,p_amount_aed:amount,p_payment_state:state});
  }else if(evt.type==='payment_intent.succeeded'){
    await db.rpc('barman_update_stripe_payment_intent',{p_payment_intent_id:String(obj.id),p_payment_state:'paid'});
  }else if(evt.type==='payment_intent.payment_failed'){
    await db.rpc('barman_update_stripe_payment_intent',{p_payment_intent_id:String(obj.id),p_payment_state:'failed'});
  }else if(evt.type==='refund.created'||evt.type==='refund.updated'){
    const pi=obj.payment_intent?String(obj.payment_intent):'';if(pi&&obj.status==='succeeded')await db.rpc('barman_update_stripe_payment_intent',{p_payment_intent_id:pi,p_payment_state:'refunded'});
  }
 }catch{return new Response('processing failed',{status:500})}
 return new Response(JSON.stringify({received:true}),{status:200,headers:{'content-type':'application/json'}});
});
