const script=String.raw`(()=>{
  if(window.__dabbirClinicModeV1)return;window.__dabbirClinicModeV1=true;
  const $=s=>document.querySelector(s), W=()=>{try{return workspace}catch{return null}}, A=()=>document.documentElement.lang!=='en';
  const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const C=()=>A()?{title:'عيادة التجميل والليزر',desc:'الجلسات والباقات والأجهزة والموافقات والتنبيه للجلسة القادمة — بدون صور.',locked:'بيانات المرضى الحقيقية مقفلة حتى اكتمال مراجعات الخصوصية والأمان. البيانات التجريبية فقط متاحة حاليًا.',session:'تسجيل جلسة',package:'إضافة باقة',device:'إضافة جهاز',consent:'الموافقات',appt:'الموعد',type:'نوع الجلسة',area:'المنطقة المعالجة',pkg:'الباقة',dev:'الجهاز',settings:'إعدادات الجهاز/الجلسة',before:'ملاحظات قبل الجلسة',after:'ملاحظات بعد الجلسة',next:'الجلسة القادمة',status:'الحالة',customer:'العميل',service:'الخدمة',name:'الاسم',sessions:'عدد الجلسات',price:'السعر',expiry:'الانتهاء',model:'الموديل',template:'نموذج الموافقة',body:'نص الموافقة',version:'الإصدار',record:'تسجيل موافقة العميل',save:'حفظ',none:'بدون',saved:'تم الحفظ',fail:'تعذر الحفظ',rem:'المتبقي'}:{title:'Beauty & Laser Clinic',desc:'Sessions, packages, devices, consents and next-session reminders — no photos.',locked:'Real patient data is locked until privacy and security reviews are complete. Synthetic data only is available now.',session:'Session record',package:'Add package',device:'Add device',consent:'Consents',appt:'Appointment',type:'Session type',area:'Treatment area',pkg:'Package',dev:'Device',settings:'Device/session settings',before:'Before notes',after:'After notes',next:'Next session',status:'Status',customer:'Client',service:'Service',name:'Name',sessions:'Sessions',price:'Price',expiry:'Expiry',model:'Model',template:'Consent template',body:'Consent text',version:'Version',record:'Record client consent',save:'Save',none:'None',saved:'Saved',fail:'Save failed',rem:'Remaining'};
  const isClinic=()=>W()?.business?.business_type==='clinic', bid=()=>W()?.business?.id;
  let D=null,busy=false;
  const style=document.createElement('style');style.textContent='.clinicV1{margin:12px 0;padding:12px;border:1px solid var(--line);border-radius:18px;background:#111315}.clinicV1 h3{margin:0 0 4px;font-size:14px}.clinicV1>p{margin:0 0 10px;color:var(--muted);font-size:9px}.clinicGate{padding:8px;border:1px solid #6b5326;border-radius:10px;background:#2b2415;color:#ffd98a;font-size:9px;margin-bottom:10px}.clinicGrid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.clinicCard{padding:10px;border:1px solid #292f34;border-radius:12px;background:#15181b}.clinicCard h4{margin:0 0 8px;font-size:11px}.clinicFields{display:grid;grid-template-columns:1fr 1fr;gap:6px}.clinicField{display:grid;gap:3px}.clinicField.full{grid-column:1/-1}.clinicField label{font-size:8px;color:var(--muted)}.clinicField input,.clinicField select,.clinicField textarea{width:100%;min-height:38px;padding:8px;border:1px solid var(--line);border-radius:9px;background:#181b1f;color:#fff;font-size:10px}.clinicField textarea{min-height:68px}.clinicBtn{margin-top:8px;min-height:36px;padding:7px 11px;border:0;border-radius:9px;background:var(--accent);color:#10130b;font-weight:850}.clinicList{display:grid;gap:4px;margin-top:7px;max-height:150px;overflow:auto}.clinicRow{padding:6px;border:1px solid #292f34;border-radius:8px;font-size:8px}@media(max-width:760px){.clinicGrid,.clinicFields{grid-template-columns:1fr}.clinicField.full{grid-column:auto}}';document.head.append(style);
  const opt=(v,l)=>'<option value="'+E(v)+'">'+E(l)+'</option>', customer=id=>(D?.customers||[]).find(x=>x.id===id), service=id=>(D?.services||[]).find(x=>x.id===id);
  const fmt=v=>{try{return new Intl.DateTimeFormat(A()?'ar-AE':'en-AE',{dateStyle:'short',timeStyle:'short',timeZone:'Asia/Dubai'}).format(new Date(v))}catch{return''}};
  const appts=()=>{const c=C();return opt('',c.none)+(D?.appointments||[]).filter(x=>x.customer_id&&x.service_id).map(x=>opt(x.id,(customer(x.customer_id)?.display_name||c.customer)+' · '+(service(x.service_id)?.name_ar||service(x.service_id)?.name||c.service)+' · '+fmt(x.starts_at))).join('')};
  const customers=()=>opt('',C().none)+(D?.customers||[]).map(x=>opt(x.id,x.display_name||C().customer)).join('');
  const services=()=>opt('',C().none)+(D?.services||[]).filter(x=>x.active!==false).map(x=>opt(x.id,x.name_ar||x.name||C().service)).join('');
  const packages=()=>opt('',C().none)+(D?.packages||[]).filter(x=>x.status==='active').map(x=>opt(x.id,x.package_name+' ('+(x.total_sessions-x.used_sessions)+' '+C().rem+')')).join('');
  const devices=()=>opt('',C().none)+(D?.devices||[]).filter(x=>x.active).map(x=>opt(x.id,x.name)).join('');
  const templates=()=>opt('',C().none)+(D?.consent_templates||[]).filter(x=>x.active).map(x=>opt(x.id,x.title_ar+' v'+x.version)).join('');
  async function api(body){const r=await fetch('/api/clinic-operations'+(body?'':'?business_id='+encodeURIComponent(bid())),{method:body?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:{'content-type':'application/json',accept:'application/json'},body:body?JSON.stringify({business_id:bid(),...body}):undefined});const p=await r.json().catch(()=>({}));if(!r.ok||!p.ok){const e=new Error(p.error||'FAILED');e.payload=p;throw e}return p}
  function iso(v){if(!v)return null;const d=new Date(v+':00+04:00');return Number.isNaN(d.getTime())?null:d.toISOString()}
  function render(){if(!isClinic()||!D)return;const c=C(),s=$('#screen-appointments');if(!s)return;let p=$('#clinicV1');if(!p){p=document.createElement('section');p.id='clinicV1';p.className='clinicV1';s.append(p)}const closed=!D.patient_data_gate?.production_patient_data_allowed;
    p.innerHTML='<h3>'+E(c.title)+'</h3><p>'+E(c.desc)+'</p>'+(closed?'<div class="clinicGate">'+E(c.locked)+'</div>':'')+'<div class="clinicGrid">'+
    '<form class="clinicCard" id="cs"><h4>'+E(c.session)+'</h4><div class="clinicFields"><div class="clinicField full"><label>'+E(c.appt)+'</label><select id="ca">'+appts()+'</select></div><div class="clinicField"><label>'+E(c.type)+'</label><select id="ct">'+opt('treatment','Treatment / علاج')+opt('consultation','Consultation / استشارة')+opt('test_patch','Test patch / اختبار')+opt('follow_up','Follow-up / متابعة')+opt('maintenance','Maintenance / صيانة')+'</select></div><div class="clinicField"><label>'+E(c.area)+'</label><input id="car"></div><div class="clinicField"><label>'+E(c.pkg)+'</label><select id="cp">'+packages()+'</select></div><div class="clinicField"><label>'+E(c.dev)+'</label><select id="cd">'+devices()+'</select></div><div class="clinicField full"><label>'+E(c.settings)+'</label><textarea id="cset"></textarea></div><div class="clinicField full"><label>'+E(c.before)+'</label><textarea id="cb"></textarea></div><div class="clinicField full"><label>'+E(c.after)+'</label><textarea id="caf"></textarea></div><div class="clinicField"><label>'+E(c.next)+'</label><input id="cn" type="datetime-local"></div><div class="clinicField"><label>'+E(c.status)+'</label><select id="cst">'+opt('completed','Completed / مكتملة')+opt('planned','Planned / مخططة')+opt('in_progress','In progress / جارية')+opt('cancelled','Cancelled / ملغية')+'</select></div></div><button class="clinicBtn">'+E(c.save)+'</button></form>'+
    '<form class="clinicCard" id="pk"><h4>'+E(c.package)+'</h4><div class="clinicFields"><div class="clinicField"><label>'+E(c.customer)+'</label><select id="pc">'+customers()+'</select></div><div class="clinicField"><label>'+E(c.service)+'</label><select id="ps">'+services()+'</select></div><div class="clinicField full"><label>'+E(c.name)+'</label><input id="pn"></div><div class="clinicField"><label>'+E(c.sessions)+'</label><input id="pt" type="number" min="1" max="100" value="6"></div><div class="clinicField"><label>'+E(c.price)+'</label><input id="pp" type="number" min="0" step="0.01"></div><div class="clinicField full"><label>'+E(c.expiry)+'</label><input id="pe" type="date"></div></div><button class="clinicBtn">'+E(c.save)+'</button><div class="clinicList">'+(D.packages||[]).slice(0,8).map(x=>'<div class="clinicRow">'+E(x.package_name)+' · '+E(c.rem)+': '+Math.max(0,x.total_sessions-x.used_sessions)+'</div>').join('')+'</div></form>'+
    '<form class="clinicCard" id="dv"><h4>'+E(c.device)+'</h4><div class="clinicFields"><div class="clinicField"><label>'+E(c.name)+'</label><input id="dn"></div><div class="clinicField"><label>'+E(c.model)+'</label><input id="dm"></div><div class="clinicField full"><label>Type</label><select id="dt">'+opt('laser','Laser / ليزر')+opt('aesthetic','Aesthetic / تجميل')+opt('other','Other / أخرى')+'</select></div></div><button class="clinicBtn">'+E(c.save)+'</button><div class="clinicList">'+(D.devices||[]).slice(0,8).map(x=>'<div class="clinicRow">'+E(x.name)+' · '+E(x.model||x.device_type)+'</div>').join('')+'</div></form>'+
    '<div class="clinicCard"><h4>'+E(c.consent)+'</h4><form id="tpl"><div class="clinicFields"><div class="clinicField"><label>'+E(c.template)+'</label><input id="tt"></div><div class="clinicField"><label>'+E(c.version)+'</label><input id="tv" value="1.0"></div><div class="clinicField full"><label>'+E(c.body)+'</label><textarea id="tb"></textarea></div></div><button class="clinicBtn">'+E(c.save)+'</button></form><form id="rc"><div class="clinicFields"><div class="clinicField"><label>'+E(c.appt)+'</label><select id="ra">'+appts()+'</select></div><div class="clinicField"><label>'+E(c.template)+'</label><select id="rt">'+templates()+'</select></div></div><button class="clinicBtn">'+E(c.record)+'</button></form></div></div>';
    $('#cs').onsubmit=e=>save(e,{action:'save_session',appointment_id:$('#ca').value,session_type:$('#ct').value,treatment_area:$('#car').value,package_id:$('#cp').value||null,device_id:$('#cd').value||null,device_settings_notes:$('#cset').value,notes_before:$('#cb').value,notes_after:$('#caf').value,next_session_at:iso($('#cn').value),status:$('#cst').value});
    $('#pk').onsubmit=e=>save(e,{action:'save_package',customer_id:$('#pc').value,service_id:$('#ps').value,package_name:$('#pn').value,total_sessions:$('#pt').value,price_aed:$('#pp').value,expires_at:$('#pe').value||null});
    $('#dv').onsubmit=e=>save(e,{action:'save_device',name:$('#dn').value,model:$('#dm').value,device_type:$('#dt').value});
    $('#tpl').onsubmit=e=>save(e,{action:'save_consent_template',title_ar:$('#tt').value,title_en:$('#tt').value,body_ar:$('#tb').value,body_en:'',version:$('#tv').value});
    $('#rc').onsubmit=e=>{const a=(D.appointments||[]).find(x=>x.id===$('#ra').value);save(e,{action:'record_consent',appointment_id:a?.id,customer_id:a?.customer_id,template_id:$('#rt').value,granted:true})};
  }
  async function save(e,b){e.preventDefault();if(busy)return;busy=true;try{await api(b);try{toast(C().saved)}catch{};await load()}catch(x){try{toast(x?.payload?.error==='PATIENT_DATA_GATE_CLOSED'?C().locked:C().fail)}catch{}}finally{busy=false}}
  async function load(){if(!isClinic()||!bid()||busy)return;try{D=await api();render()}catch(e){console.error('clinic_mode_load',e)}}
  const mo=new MutationObserver(()=>{if(isClinic()&&$('#screen-appointments')?.classList.contains('active'))load()});mo.observe(document.body,{subtree:true,attributes:true,attributeFilter:['class'],childList:true});setTimeout(load,700);window.__dabbirClinicMode={refresh:load,version:'beauty-laser-v1-no-images'};
})();`;
export default function handler(req,res){if(req.method!=='GET')return res.status(405).setHeader('allow','GET').end('Method Not Allowed');res.setHeader('content-type','application/javascript; charset=utf-8');res.setHeader('cache-control','public, max-age=300');res.setHeader('x-dabbir-clinic-mode','beauty-laser-v1-no-images');return res.status(200).send(script)}
